import os

TOKEN = os.getenv('TOKEN_EURODOLLAR')
DB_USER = os.getenv('DB_USER_EURODOLLAR')
DB_NAME = os.getenv('DB_NAME_EURODOLLAR')
DB_PASSWORD = os.getenv('DB_PASSWORD_EURODOLLAR')
DB_HOST = os.getenv('DB_HOST_EURODOLLAR')
